apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: nats
spec:
  project: default
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    chart: nats
    targetRevision: 1.2.6
          
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true