apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: cp-helm-charts
    repoURL: https://confluentinc.github.io/cp-helm-charts/
    targetRevision: 0.6.1
    helm:
      values: |
        cp-zookeeper:
          enabled: true
          servers: 3
          persistence:
            enabled: true
            size: 5Gi
          
        cp-kafka:
          enabled: true
          brokers: 3
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1000m"
          
        cp-schema-registry:
          enabled: true
          
        prometheus:
          jmx:
            enabled: true
            
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true