# kafka-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 31.0.0
    helm:
      values: |
        replicaCount: 3
        persistence:
          enabled: true
          size: 5Gi
        zookeeper:
          enabled: true
          replicaCount: 3
          persistence:
            enabled: true
            size: 5Gi
        metrics:
          kafka:
            enabled: true
          zookeeper:
            enabled: true
        serviceAccount:
          create: true
        rbac:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true